#!/usr/bin/env php
<?php
/*
 * This is some code I worked on, that should be able to discover Sonos devices. The problem is that it requires PHP5.4
 */
$multicast_addr = '239.255.255.250';
$multicast_port = 1900;
$timeout = 1;
$search_message = "M-SEARCH * HTTP/1.1
HOST: " . $multicast_addr . ":reservedSSDPport
MAN: ssdp:discover
MX: " . $timeout . "
ST: urn:schemas-upnp-org:device:ZonePlayer:1";

$socket = socket_create(AF_INET, SOCK_DGRAM, SOL_UDP);
socket_set_option($socket, SOL_SOCKET, IP_MULTICAST_TTL, 2);

socket_sendto($socket, $search_message, strlen($search_message), 0, $multicast_addr, $multicast_port);

while (true) {
    echo socket_recvfrom($socket, $search_message, 0, $multicast_port, $multicast_addr); 
}
